"""Add architecture table

Revision ID: 40312da8cc55
Revises: 2d1aa7ff82a5
Create Date: 2024-03-05 09:58:26.306444
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '40312da8cc55'
down_revision = '2d1aa7ff82a5'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_architectures',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('architecture', sa.String(length=50), nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('project_id', 'architecture')
    )
    op.add_column('projects', sa.Column('architecture_url', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('tag', sa.String(length=200), nullable=True))
    op.add_column('projects_versions', sa.Column('oe_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_versions', 'oe_version')
    op.drop_column('projects', 'tag')
    op.drop_column('projects', 'architecture_url')
    op.drop_table('projects_architectures')
    # ### end Alembic commands ###
