"""add unique constraint in project architecture

Revision ID: bf3813db9dc7
Revises: 40312da8cc55
Create Date: 2024-03-12 16:02:04.247706
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "bf3813db9dc7"
down_revision = "40312da8cc55"


def upgrade():
    """commands auto generated by Alembic - please adjust!"""
    op.create_unique_constraint(
        "projects_architectures_unique_project_id",
        "projects_architectures",
        ["project_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    """commands auto generated by Alembic - please adjust!"""
    op.drop_constraint(
        "projects_architectures_unique_project_id",
        "projects_architectures",
        type_="unique",
    )
    # ### end Alembic commands ###
